### ISSUE TITLE
所以为什么不把网页版放到你的网站上面

### ISSUE THREAD

**Issue by kuqilin** [Buelie/3306_Other#1]

**Comment by Buelie** [comment]
e,我现在部署一下,website库那

**Comment by Buelie** [comment]
目前已部署，网址: https://buelie.github.io/websites/3306/
@kuqilin 

> **注意：仅能连接公网服务器，不能连接本地服务器（如需连接本地服务器，请下载服务端及相应客户端源代码，无需配置Node.js环境）**

**Comment by Buelie** [comment]
https://buelie.github.io/websites/3306/  请不要在该项目提issue，请到主项目https://github.com/Buelie/3306提issue
